routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->middleware('auth');

//Admin Routes
Auth::routes();


Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');

Route::group([
    'middleware' => ['auth']
], function () {

    Route::get('/home', 'HomeController@index');
    Route::post('organisation/join_org', 'OrganisationController@join_org');
    Route::post('organisation/cancel_org', 'OrganisationController@cancel_org');
    Route::resource('organisation', 'OrganisationController');
    Route::resource('shift', 'ShiftController');
    

});

app/Http/Controllers/OrganisationController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Model\Organisation;
use App\Model\OrganisationUsers;
use App\Model\User;
use Auth;

class OrganisationController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $id = Auth::user()->id;
        $user = User::findOrFail($id);
        $organisations_all = Organisation::all();

        $allOfUsers = $user->organisations;

        $organisations = $organisations_all->diff($allOfUsers);

        return view('organisation/home', compact('organisations', 'user'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $id = Auth::user()->id;
        $user = User::findOrFail($id);
        return view('organisation/create', compact('user'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Organisation $organisation,Request $request)
    {
        $request->validate([
            'name'=>'required',
            'hourly_rate'=> 'required'
        ]);
        $organisation->name = $request->get('name');
        $organisation->hourly_rate = $request->get('hourly_rate');

        $organisation->save();

        return redirect()->route('organisation.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
           

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $auth_id = Auth::user()->id;
        $user = User::findOrFail($auth_id);
        $organisation = Organisation::findOrFail($id);
        return view('organisation/edit', compact('organisation', 'user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name'=>'required',
            'hourly_rate'=> 'required'
        ]);

        $organisation = Organisation::find($id);
        $organisation->name = $request->get('name');
        $organisation->hourly_rate = $request->get('hourly_rate');

        $organisation->save();

        return redirect()->route('organisation.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function join_org(OrganisationUsers $organisationUsers, Request $request)
    {
        
        $organisationUsers->organisation_id = $request->o_id;
        $organisationUsers->user_id = Auth::user()->id;
        $organisationUsers->save();

        return redirect()->route('organisation.index');
    }

    public function cancel_org(OrganisationUsers $organisationUsers, Request $request)
    {
        
        $whereArray = array('user_id' => Auth::user()->id,'organisation_id' => $request->o_id);
        $res = OrganisationUsers::where($whereArray)->delete();

        return redirect()->back();
    }
}

resources/views/organisation/create.blade.php
@extends('layouts.app-auth')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Create an Organisation</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('organisation.store') }}">
                        @csrf

                        <div class="form-group row">
                            <label for="email" class="col-md-4 col-form-label text-md-right">Name</label>

                            <div class="col-md-6">
                                <input id="name" type="text" name="name" placeholder="Name" required autofocus>

                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="email" class="col-md-4 col-form-label text-md-right">Hourly Rate</label>

                            <div class="col-md-6">
                                $ <input id="hourly_rate" type="number" name="hourly_rate" placeholder="0.00" required autofocus>
                                per hour
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-8 offset-md-4">
                                <button type="submit" class="btn btn-success">
                                    Save
                                </button>

                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/organisation/edit.blade.php
@extends('layouts.app-auth')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Update Organisation</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('organisation.update', $organisation->id) }}">
                        @method('PATCH')
                        @csrf

                        <div class="form-group row">
                            <label for="email" class="col-md-4 col-form-label text-md-right">Name</label>

                            <div class="col-md-6">
                                <input id="name" type="text" name="name" value="{{ $organisation->name }}" placeholder="Name" required autofocus>

                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="email" class="col-md-4 col-form-label text-md-right">Hourly Rate</label>

                            <div class="col-md-6">
                                $ <input id="hourly_rate" type="number" value="{{ $organisation->hourly_rate }}" name="hourly_rate" placeholder="0.00" required autofocus> per hour

                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-8 offset-md-4">
                                <button type="submit" class="btn btn-success">
                                    Save
                                </button>

                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/organisation/home.blade.php
@extends('layouts.app-auth')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">

            <div class="card">
                <div class="card-header">Organisations <a class="btn btn-success float-right" href="organisation/create">
                  New Organisation
                </a></div>

                <div class="card-body">
                    <table id="example" class="table table-striped table-bordered" style="width:100%">
				        <thead>
				            <tr>
				                <th>Name</th>
                                <th>Hourly Rate</th>
				                <th>Actions</th>
				            </tr>
				        </thead>
                        <tbody>
                            @foreach ($organisations as $organisation)
                            <tr>
                                <td>{{ $organisation->name }}</td>
                                <td>$ {{ $organisation->hourly_rate }}</td>
                                <td>
                                	&nbsp;&nbsp;
                                	<form method="post" class="float-right" action="organisation/join_org">
                                		@csrf
                                		<input type="hidden" name="o_id" value="{{ $organisation->id }}"/>
                                		<button type="submit" class="btn btn-success">Join</button>
                                	</form>
					                &nbsp;&nbsp;
					                <a class="btn btn-warning float-right" href="{{ route('organisation.edit',$organisation->id) }}">
					                  Edit
					                </a>
					                &nbsp;&nbsp;
                                </td>
                            </tr>

                            @endforeach
                        </tbody>
				    </table>
                </div>
            </div>
        </div>
    </div>
</div>


<script>
$(document).ready(function() {
    $('#example').DataTable();
} );
</script>

@endsection