routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->middleware('auth');

//Admin Routes
Auth::routes();


Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');

Route::group([
    'middleware' => ['auth']
], function () {

    Route::get('/home', 'HomeController@index');
    Route::post('organisation/join_org', 'OrganisationController@join_org');
    Route::post('organisation/cancel_org', 'OrganisationController@cancel_org');
    Route::resource('organisation', 'OrganisationController');
    Route::resource('shift', 'ShiftController');
    

});

app/Http/Controllers/ShiftController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Model\Organisation;
use App\Model\OrganisationUsers;
use App\Model\User;
use App\Model\Shift;
use Auth;

class ShiftController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Shift $shift)
    {
        $request->validate([
            'user_id'=>'required',
            'shift_date'=> 'required',
            'start_time'=> 'required',
            'finish_time'=> 'required',
            'break_length'=> 'required',
            'o_id' => 'required',
        ]);

        $shift->user_id = $request->get('user_id');
        $shift->organisation_id = $request->get('o_id');
        $shift->shift_date = $request->get('shift_date');
        $shift->start_time = $request->get('start_time');
        $shift->finish_time = $request->get('finish_time');
        $shift->break_length = $request->get('break_length');

        $shift->save();

        return redirect()->back();

    }
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $auth_id = Auth::user()->id;
        $user = User::findOrFail($auth_id);

        $organisation = Organisation::findOrFail($id);

        $users = $organisation->users;
        $o_id = $id;
        $org_name = $organisation->name;

        $org_hourly_rate = $organisation->hourly_rate;


        $shifts = Shift::ofOrganisationId($id)->get();

        $listShifts = [];
        $x = 0;
        foreach ($shifts as $shift) {

            $employee = User::findOrFail($shift->user_id);

            $listShifts[$x]['name'] = $employee->name;

            $listShifts[$x]['id'] = $shift->id;



            $listShifts[$x]['shift_date'] = date('M d, Y', strtotime($shift->shift_date));

            $listShifts[$x]['start_time'] = date('h:i a', strtotime($shift->start_time));
            $listShifts[$x]['finish_time'] = date('h:i a', strtotime($shift->finish_time));

            $totalWS = 0;

            $rate = 0;

            

            if(date('N', strtotime($shift->shift_date)) == 7){
                if(strtotime($shift->start_time) > strtotime($shift->finish_time)){

                   
                    $time1 = strtotime($shift->start_time);
                    $time2 = strtotime('24:00:00');
                    $difference1 = round(abs($time2 - $time1) / 3600,2);
                    $doubled = $difference1 * $org_hourly_rate * 2;

                    $time3 = strtotime($shift->finish_time);
                    $time4 = strtotime('00:00:00');


                    $difference2 = (round(abs($time3 - $time4) / 60,2) - $shift->break_length)/ 60;
                    $basic = $difference2 * $org_hourly_rate;

                    if($difference2 < 0){
                        $rate = ($difference1 + $difference2) * $org_hourly_rate * 2;
                    }else{
                        $rate = $doubled + $basic;
                    }
                    

                    $listShifts[$x]['total_ws'] = number_format($difference1 + $difference2, 2);

                }else{
                    $totalWS = strtotime($shift->finish_time) - strtotime($shift->start_time);

                    $rate = number_format((((($totalWS/60) - $shift->break_length)/60) * $org_hourly_rate)*2, 2);
                    $listShifts[$x]['total_ws'] = number_format((($totalWS/60) - $shift->break_length)/60, 2);
                }
            }else{
                if(strtotime($shift->start_time) > strtotime($shift->finish_time)){

                    $totalWS = strtotime($shift->finish_time . ' +1 day') - strtotime($shift->start_time);

                }else{
                    $totalWS = strtotime($shift->finish_time) - strtotime($shift->start_time);
                }

                $rate = number_format(((($totalWS/60) - $shift->break_length)/60) * $org_hourly_rate, 2);

                $listShifts[$x]['total_ws'] = number_format((($totalWS/60) - $shift->break_length)/60, 2);
            }



            

            $listShifts[$x]['break_length'] = $shift->break_length;
            $listShifts[$x]['total_pay'] = number_format($rate,2);

            $x++;
        }



        return view('shift/list', compact('users', 'user', 'o_id', 'org_name', 'listShifts')); 
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $shift = Shift::findOrFail($id);

        $auth_id = Auth::user()->id;
        $user = User::findOrFail($auth_id);

        $employee = User::findOrFail($shift->user_id);

        $emp_name = $employee->name;

        return view('shift/edit', compact('user', 'shift', 'emp_name'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'shift_date'=> 'required',
            'start_time'=> 'required',
            'finish_time'=> 'required',
            'break_length'=> 'required'
        ]);

        $shift = Shift::find($id);

        $oid = $shift->organisation_id;

        $shift->shift_date = $request->get('shift_date');
        $shift->start_time = $request->get('start_time');
        $shift->finish_time = $request->get('finish_time');
        $shift->break_length = $request->get('break_length');

        $shift->save();

        return redirect()->route('shift.show', $oid);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        
        $shift = Shift::find($id);
        $shift->delete();


        return redirect()->back();
    }
}

resources/views/shift/edit.blade.php
@extends('layouts.app-auth')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Update Organisation</div>

                <div class="card-body">
                    
                            <form method="post" action="{{ route('shift.update', $shift['id']) }}">
                                @method('PUT')
                                @csrf

                                <div class="form-group row">
                                    <label for="email" class="col-md-4 col-form-label text-md-right">Name</label>

                                    <div class="col-md-6">
                                        {{ $emp_name }}
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label for="email" class="col-md-4 col-form-label text-md-right">Shift Date</label>

                                    <div class="col-md-6">
                                        <input id="shift_date" type="date" value="{{ $shift['shift_date'] }}" name="shift_date" required autofocus>
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label for="email" class="col-md-4 col-form-label text-md-right">Start Time</label>

                                    <div class="col-md-6">
                                        <input id="start_time" value="{{ $shift['start_time'] }}" type="time" name="start_time" required autofocus>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="email" class="col-md-4 col-form-label text-md-right">Finish Time</label>

                                    <div class="col-md-6">
                                        <input id="finish_time" value="{{ $shift['finish_time'] }}" type="time" name="finish_time" required autofocus>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="email" class="col-md-4 col-form-label text-md-right">Break Length (Mins)</label>

                                    <div class="col-md-6">
                                        <input id="break_length" value="{{ $shift['break_length'] }}" type="number" name="break_length" placeholder="0" required autofocus>
                                    </div>
                                </div>
                                

                                <div class="form-group row mb-0">
                                    <div class="col-md-8 offset-md-4">
                                        <button type="submit" class="btn btn-success">
                                            Save
                                        </button>

                                    </div>
                                </div>
                                
                            </form>

                            
                </div>
            </div>
        </div>
    </div>
</div>


<script>
$(document).ready(function() {
    $('#example').DataTable();
} );
</script>

@endsection

resources/views/shift/list.blade.php
@extends('layouts.app-auth')

@section('content')
<style>
    .table th, .table td {
        padding: 0.4rem!important;
    }
</style>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">

            <div class="card">
                <div class="card-header">{{ $org_name }}</div>

                <div class="card-body">
                    <table id="example" class="table table-striped table-bordered" style="width:100%">
				        <thead>
				            <tr>
				                <th>Name</th>
                                <th>Shift Date</th>
				                <th>Start Time</th>
                                <th>Finish Time</th>
                                <th>Break Length <br/>(Mins)</th>
                                <th>Worked Hours</th>
                                <th>Shift Cost</th>
                                <th>Actions</th>
				            </tr>
				        </thead>
                        <tbody>
                            @foreach ($listShifts as $shift)
                            <tr>
                                <td>{{ $shift['name'] }}</td>
                                <td>{{ $shift['shift_date'] }}</td>
                                <td>{{ $shift['start_time'] }}</td>
                                <td>{{ $shift['finish_time'] }}</td>
                                <td>{{ $shift['break_length'] }}</td>
                                <td>{{ $shift['total_ws'] }}</td>
                                <td>$ {{ $shift['total_pay'] }}</td>
                                <td>
                                    <a class="btn btn-warning float-left" href="{{ route('shift.edit', $shift['id']) }}">
                                      Edit
                                    </a>
                                    <br/>
                                    <form method="post" class="float-left" action="{{ route('shift.destroy', $shift['id']) }}">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-danger">Remove</button>
                                    </form>
                                </td>
                            </tr>
                            @endforeach

                            <form method="post" class="float-right" action="{{ route('shift.store') }}">
                                @csrf
                                <tr>
                                    <td>
                                        <input type="hidden" name="user_id" value="{{ $user->id }}"/>
                                        {{ $user->name }}
                                    </td>
                                    <td>
                                        <input id="shift_date" type="date" name="shift_date" required autofocus>
                                    </td>
                                    <td>
                                        <input id="start_time" type="time" name="start_time" required autofocus>
                                    </td>
                                    <td>
                                        <input id="finish_time" type="time" name="finish_time" required autofocus>
                                    </td>
                                    <td>
                                        <input id="break_length" type="number" name="break_length" placeholder="0" required autofocus>
                                    </td>
                                    
                                    <td colspan="3">
                                    	<input type="hidden" name="o_id" value="{{ $o_id }}"/>
                                    	<button type="submit" class="btn btn-success">Create Shift</button>
                                    	
                                    </td>
                                </tr>
                            </form>

                            
                        </tbody>
				    </table>
                </div>
            </div>
        </div>
    </div>
</div>


<script>
$(document).ready(function() {
    $('#example').DataTable();
} );
</script>

@endsection